[WIP]passage vue-cli
Les-Poros/Juke-in-the-box-apps pull request #2
Opened 2019-02-27 19:15 UTC by QuentinRimet

2019-02-27 19:21 UTC, QuentinRimet commented
@Luwangel on à décider de repartir sur vue-cli webpack + vue router a partir de tes conseils.
Cependant un problème se pose. En utilisant la commande "npm run dev" l'application se lance comme prévu et sans erreur.
Cependant je n'arrive pas à le faire marcher directement a partir du "npm run build" , la page html me répondant 
![image](https://user-images.githubusercontent.com/34107613/53516670-1fef6480-3acd-11e9-8d81-cd3e50c66046.png) 
Pourtant le build devrait bien marcher si il fonctionne en mode dev
Du coup si tu avais des conseils à ce propos (et aussi au niveau du code à améliorer)

2019-03-01 12:30 UTC, Luwangel reviewed
C'est un super point d'avoir commencé la migration de votre application avec vuejs. je trouve le code mieux organisé.

Il ne reste plus qu'à faire la même chose pour la seconde application =)

J'ai posté des remarques un peu plus génériques sur vuejs, vous n'êtes pas obligé de tout faire pour le moment, mais cela vous donne quelques bonnes pratiques :).


PS: les noms de variable avec des accents c'est quand même très moyen...

2019-03-01 13:00 UTC, Luwangel requested changes

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/main.js
> +    url : "https://webetu.iutnc.univ-lorraine.fr/www/rimet2u/jukeinthebox/",
Vous pouvez déporter cette config dans un fichier de config.

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/main.js
> +<div class="index">
Je ne comprends pas bien l'intérêt d'avoir un écran avec un bouton "Accéder à l'application". Si on lance l'app, c'est qu'on veut l'ouvrir. Ouvez donc directement la route `/accueil`.

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/main.js
> +    entrerToken : function(){
Vous devriez gérer l'authentification directement dans les routes en question, et rediriger vers une page pour que l'utilisateur entre son token s'il n'est pas authentifié.

https://scotch.io/tutorials/vue-authentication-and-route-handling-using-vue-router
https://router.vuejs.org/guide/advanced/data-fetching.html

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/main.js
> +},created(){
Vous n'avez pas besoin de déclarer une fonction vide pour chaque mot clef. Le principe de vuejs est simple: si vous n'utilisez pas une méthode, ne la déclarez pas.

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/Bibliotheque.vue
> +          let lien = window.location.toString().split("bibliotheque");
Je pense que vue-router propose des méthodes pour récupérer des données depuis l'url. Vous devriez les utiliser.

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/Bibliotheque.vue
> +      if (this.$parent.tokenValide()) {
C'est un antipatern que d'utiliser this.$parent. Si vous avez besoin d'un paramètre ou d'une méthode du parent, ils doivent venir via des props.

Je vous conseiller de regarder du côté de [vuex](https://vuex.vuejs.org).

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/Bibliotheque.vue
> +          let lien = window.location.toString().split("bibliotheque");
Je l'ai mis en place dans ce projet : https://github.com/Luwangel/15-puzzle-vue/tree/master/packages/app, cela peut vous donner une idée.

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/File.vue
> +            <span v-for="(artiste,index) in musique.piste.artistes">
J'ai un avertissement en console : "elements in iteration expect to have 'v-bind:key' directives".

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/File.vue
> +                v-if="index != Object.keys(musique.piste.artistes).length - 1"
Vous pouvez créer des propriétés "computed" pour gérer ce genre de conditions.

2019-03-01 13:00 UTC, Luwangel commented on jukeInTheBoxUti/www/src/Accueil.vue
> +      <section v-if="musique=='aucune'">
Utilisez plutôt la stricte égalité en javascript ===

2019-03-01 14:45 UTC, QuentinRimet commented on jukeInTheBoxUti/www/src/File.vue
> +                v-if="index != Object.keys(musique.piste.artistes).length - 1"
ca serait des propriétés qui retourerait juste
"Object.keys(musique.piste.artistes).length - 1" c'est ca ?

2019-03-01 16:56 UTC, Luwangel commented on jukeInTheBoxUti/www/src/File.vue
> +                v-if="index != Object.keys(musique.piste.artistes).length - 1"
Je vois deux objectifs à cela. Le premier est la lisibilité du template. Le second c'est de gagner en performance. En effet, cela évite de recalculer ce champ à chaque rendu des éléments de la liste.

2019-03-05 21:17 UTC, QuentinRimet commented
@Luwangel 
Ok j'ai pris en compte les recommandations (sauf pour l'url dans un fichier extérieur et j'ai remplacé les computed par un truc plus simple et normalement plus opti). Comme d'hab c'est surtout au niveau de la gestion du token qu'il faut regarder.

Je travaillerais sur la version du barman demain (qui est presque comme la version cli)

2019-03-07 17:01 UTC, Luwangel requested changes

2019-03-07 17:01 UTC, Luwangel commented on jukeInTheBoxUti/www/src/main.js
> +    url : "https://webetu.iutnc.univ-lorraine.fr/www/rimet2u/jukeinthebox/"
It's not a problem to use data to store the url, but the link you come from a separate config file. And the name `url` is bad because it's too ambiguous. You can use `apiUrl` instead. This will look like:

``` js
import config from './config';

/* [...] */

const app = new Vue({
    router,
    data: {
        apiUrl: config.apiUrl,
    },
});

app.mount('.app');
```

2019-03-07 17:01 UTC, Luwangel commented on jukeInTheBoxUti/www/src/main.js
> +router.beforeEach((to, from, next) => {
You have two else which do the same thing. You could refact your code like this:

``` js
router.beforeEach((to, from, next) => {
    if (
        to.matched.some(record => record.path !== '/login') &&
        localStorage.token == null
    ) {
        next({
            name: 'Login',
            params: { nextUrl: to.fullPath },
        });
    } else {
        next();
    }
});
```

Note that I use [prettier](https://github.com/prettier/prettier) to format my code. I recommend you to install it at least on you code editor.

2019-03-07 17:01 UTC, Luwangel commented on jukeInTheBoxUti/www/src/Login.vue
> +  /* Hidden by default */
Tu n'es pas besoin de commenté toutes les lignes, seulement celles qui sont particulières. Le code doit se suffire à lui même.

2019-03-07 17:01 UTC, Luwangel commented on jukeInTheBoxUti/www/src/Login.vue
> +    //permet de valider la saisie d'un token
Ce commentaire ne devrait pas être nécessaire. S'il l'est, c'est que le nom de la méthode n'est pas assez bien choisi.

2019-03-07 17:01 UTC, Luwangel commented on jukeInTheBoxUti/www/src/File.vue
> +      return
???

2019-03-07 20:54 UTC, Luwangel commented on jukeInTheBoxBar/www/src/addBiblio.vue
> +<template>
Je ne comprends pas la différence entre ce composant et le composant `Bibliothèque`.

2019-03-07 20:54 UTC, Luwangel commented on jukeInTheBoxBar/www/src/addBiblio.vue
> +  background: linear-gradient(top, #456072 0%, #2c4759 100%);
Je pense que VueJS implémente un autoprefixer ce qui évite de déclarer ce style pour tous les navigateurs. De plus, vu que vous faites du mobile, pas besoin de s'embêter trop avec ça :)

2019-03-07 20:54 UTC, Luwangel commented on jukeInTheBoxBar/www/src/main.js
> +const menuBiblio={template : `
N'oubliez pas de déplacer ce composant dans un fichier à part

2019-03-08 12:27 UTC, QuentinRimet commented on jukeInTheBoxBar/www/src/addBiblio.vue
> +<template>
addBiblio et Bibliotheque possedent le meme templates et css mais on des fonctions différentes.
L'un est pour ajouter un musique a sa bibliotheque, l'autre permet de voir sa bibliotheque et d'en retirer une musique.

2019-03-08 12:34 UTC, QuentinRimet commented on jukeInTheBoxBar/www/src/addBiblio.vue
> +<template>
je n'ai pas trouvé de solution pour exporter le template afin de le réutiliser dans différents composants.
j'ai aussi pensé à utiliser le meme composant pour les 2 routes et on lance les fonctions spécifiques en fonction de la route actuelle mais je me dit que c'est un peu perdre la notion de composant (pas reutilisable sans modifications du code sur une autre route)

2019-03-25 12:22 UTC, merged